version: '3'
services:
    php:
        build: ./docker/php
        container_name: us_debt_php
        restart: always
        volumes:
            - .:/var/www/html
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini

    php_cli:
        build: ./docker/php_cli
        container_name: us_debt_php_cli
        restart: always
        volumes:
            - .:/var/www/html
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./docker/php_cli/mycrontab:/crontab

    nginx:
        image: nginx:1.17-alpine
        container_name: us_debt_nginx
        restart: always
        ports:
            - ${NGINX_EXPOSE_PORT}:80
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
