version: '3'
services:
    php:
        build:
            context: ./docker/php
            args:
                - TZ
                - UID
                - GID
        container_name: us_debt_php
        restart: always
        volumes:
            - .:/var/www/html
            - ./docker/php/crontab:/crontab:ro
            - ./docker/php/conf.d/php-${APP_ENV}.ini:/usr/local/etc/php/conf.d/php.ini:ro
