imports:
    - { resource: parameters.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # > Common

    App\:
        resource: '../src/*'

    Symfony\Component\Filesystem\Filesystem: ~

    Symfony\Contracts\HttpClient\HttpClientInterface:
        class: Symfony\Component\HttpClient\NativeHttpClient

    # > Common

    # > Serializer

    App\Service\Serializer\SerializerBuilder:
        factory: ['App\Serializer\SerializerBuilder', 'create']
        calls:
            - ['addSubscribingHandler', ['@App\EventSubscriber\Serializer\FileHandler']]

    JMS\Serializer\SerializerInterface:
        factory: ['@App\Serializer\SerializerBuilder', 'build']

    App\EventSubscriber\Serializer\FileHandler: ~

    # < Serializer

    # > Console

    app.console:
        public: true
        class: App\Console\Application
        arguments:
            $name: '%app.name%'
        calls:
            - [add, ['@App\Command\AppDebug']]

    App\Command\:
        public: true
        resource: '../src/Command/*'
        tags: ['console.command']

    App\Command\AppDebug: ~

    # < Console

    # > Accounting

    App\Service\Accounting\USDebtAmountProvider:
        arguments:
            $url: '%app.accounting.us_debt.url%'

    # < Accounting

    # > Image

    App\Service\Image\Builder\USDebtImageBuilder:
        arguments:
            $backgroundPathname: '%app.image.builder.us_debt.background_pathname%'
            $fontPathname: '%app.image.builder.us_debt.font_pathname%'
            $fontColor: '%app.image.builder.us_debt.font_color%'

    # < Image

    # > Telegram

    App\Service\Telegram\Api:
        arguments:
            $apiToken: '%env(APP_TELEGRAM_API_TOKEN)%'

    # < Telegram
