imports:
    - { resource: parameters.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # > Common

    App\:
        resource: '../src/*'

    Symfony\Component\Filesystem\Filesystem: ~

    Symfony\Component\Stopwatch\Stopwatch: ~

    Symfony\Contracts\HttpClient\HttpClientInterface:
        class: Symfony\Component\HttpClient\NativeHttpClient

    JMS\Serializer\SerializerBuilder:
        factory: ['JMS\Serializer\SerializerBuilder', 'create']

    JMS\Serializer\SerializerInterface:
        factory: ['@JMS\Serializer\SerializerBuilder', 'build']

    TuriBot\Client:
        arguments:
            $token: '%env(APP_TELEGRAM_BOT_API_TOKEN)%'

    # > Common

    # > Console

    app.console:
        public: true
        class: App\Console\Application
        arguments:
            $name: '%app.name%'
        calls:
            - ['add', ['@App\Command\Publisher\PublishUSDebtTelegramStickerCommand']]
            - ['add', ['@App\Command\Publisher\PublishUSDebtTelegramStickerSetCommand']]

    App\Command\:
        public: true
        resource: '../src/Command/*'
        tags: ['console.command']

    App\Command\Publisher\PublishUSDebtTelegramStickerCommand: ~
    App\Command\Publisher\PublishUSDebtTelegramStickerSetCommand: ~

    # < Console

    # > Accounting

    App\Service\Accounting\USDebtAmountProvider:
        arguments:
            $url: '%app.accounting.us_debt.url%'

    # < Accounting

    # > Image

    App\Service\Image\Builder\USDebtImageBuilder:
        arguments:
            $backgroundPathname: '%app.image.builder.us_debt.background_pathname%'
            $fontPathname: '%app.image.builder.us_debt.font_pathname%'
            $fontColor: '%app.image.builder.us_debt.font_color%'

    # < Image

    # > Publisher

    App\Service\Publisher\USDebtTelegramStickerPublisher:
        arguments:
            $userId: '%app.publisher.us_debt.telegram.sticker.user.id%'
            $setName: '%app.publisher.us_debt.telegram.sticker.set.name%'
            $emojis: '%app.publisher.us_debt.telegram.sticker.emojis%'


    App\Service\Publisher\USDebtTelegramStickerSetPublisher:
        arguments:
            $userId: '%app.publisher.us_debt.telegram.sticker.user.id%'
            $setName: '%app.publisher.us_debt.telegram.sticker.set.name%'
            $setTitle: '%app.publisher.us_debt.telegram.sticker.set.title%'
            $emojis: '%app.publisher.us_debt.telegram.sticker.emojis%'

    # < Publisher
